### ISSUE TITLE
Importing raster2xyz in Python 3.5

### ISSUE THREAD

**Issue by MohanaRC** [cayetanobv/raster2xyz#1]
Importing raster2xyz.raster2xyz in Python3.5 throws the following error,

from raster2xyz.rastert2xyz import Raster2xyz as r
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>

While trying the same thing in Python 2.7.12 works properly. 
Is there some issue regarding using the package this package in Python3?

**Comment by cayetanobv** [comment]
Hi @MohanaRC ,

This package works properly in Python 3.4, 3.5 and 3.6. I'm using Travis CI to check each new version does not fail. You can see last build passed for version 0.1.3:
https://travis-ci.org/cayetanobv/raster2xyz

All Python 3 versions supported (3.4, 3.5 and 3.6) are passing tests without errors.

Some questions about your error:
- Did you installed this package from pip?
- Could you copy & paste entire traceback error?
- What is the OS (Win, Mac, Linux) you are trying to run raster2xyz in?

Thanks for using raster2xyz.

Cayetano

**Comment by MohanaRC** [comment]
Hi @cayetanobv ..
Thanks for your response.
I had installed the package from pip but there was an issue with my installation. I reinstalled it and it works fine.

**Comment by cayetanobv** [comment]
Perfect!
