### ISSUE TITLE
Suppress output from rtxyz.translate

### ISSUE THREAD

**Issue by AndrewCunliffe** [cayetanobv/raster2xyz#3]
Are there any flags that could be used to suppress the output from rtxyz.translate? 

This is a great tool, but I'd like to not return the information below to the console for every itteration!

[2020-03-03 03:12:04 - INFO] - Getting XYZ data...
[2020-03-03 03:12:04 - INFO] - Getting geotransformed coordinates...
[2020-03-03 03:12:04 - INFO] - Building XYZ data...
[2020-03-03 03:12:04 - INFO] - New XYZ (csv file) created...

**Comment by cayetanobv** [comment]
Hi @AndrewCunliffe ,

You can pass `verbose` argument to `False` when it's instantiated Raster2xyz object:

```Python
from raster2xyz.raster2xyz import Raster2xyz

input_raster = "input_raster.tif"
out_csv = "/tmp/out_xyz.csv"

rtxyz = Raster2xyz(verbose=False)
rtxyz.translate(input_raster, out_csv)
```

Thanks,

**Comment by AndrewCunliffe** [comment]
That's perfect, thanks so much.
